# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89bb10ab1a4f46b1ff0bb435f7462be1ee3d645bde7be5221fc1372a03129c90dc95b5d22b23e26e8823e1748d06f0fbbba2bbb2bf486428b69d4ee2a87d532c

test:
  secret_key_base: 107554222ecfced6af3f95862dc91101aa058a156ca29728c9d716a7e80a899fc0085b7ac8a12dde81d62a6291493f3fff9ef4663cf2ff177d9efaa9e823508c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
